Services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db
  catalogue:
     image: catalogue:v1
     container_name: catalogue
     depends_on:
      - mongodb
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis:/data
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
      volumes:
        - rabbitmq:/var/lib/rabbitmq
  user:
    image: user:v1
    container_name: user
    depends_on:
      - redis
      - mongodb
  cart:
    image: cart:v1
    container_name: cart
    depends_on:
     - redis
     - catalogue
  shipping:
   image: shipping:v1
   container_name: shipping
   depends_on:
    - mysql
    - cart
  payment:
   image: payment:v1
   container_name: payment
   depends_on:
    - user
    - cart
    - rabbitmq
  mysql:
    image: mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  frontend:
    image: frontend:v1
    container_name: frontend  
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - cart
      - user
      - payment
      - shipping
networks:
  default:
   driver: bridge
   name: roboshop
   external: false
volumes:
   mongodb:  #docker create volume mongodb
   mysql:    #docker create volume mysql
   redis:    #docker create volume redis
   rabbitmq: #docker create volume rabbitmq

#docker compose up -d
